# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XM直播' do
 use_frameworks!

pod 'Alamofire'
pod 'Kingfisher'
pod 'SnapKit'
pod 'MJExtension'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 4.1.0'
pod 'FLAnimatedImage', '~> 1.0.12'
pod 'ProtocolBuffers-Swift', '~> 3.0.6'
pod 'ReachabilitySwift', '~> 3'
pod 'GPUImage', '~> 0.1.7' 

end
